{
 "title": "AWS Infrastructure",
 "refresh": "5s",
 "panels": [
  {
   "title": "RDS CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "${rds_identifier}" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS Freeable Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "${rds_identifier}" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "default",
     "statistic": "Average",
     "id": "queryA"
    }
   ]
  },
  {
   "title": "RDS Free Storage Space (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "${rds_identifier}" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "default",
     "statistic": "Average",
     "id": "queryA"
    }
   ]
  },
  {
   "title": "ELB Healthy Host Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "${alb_arn_suffix}", "TargetGroup": "${target_group_arn_suffix}" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "region": "default",
     "statistic": "Average",
     "id": "queryA"
    }
   ]
  },
  {
   "title": "ELB 4XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "${alb_arn_suffix}" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "region": "default",
     "statistic": "Sum",
     "id": "queryA"
    }
   ]
  },
  {
   "title": "ELB 5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "${alb_arn_suffix}" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "region": "default",
     "statistic": "Sum",
     "id": "queryA"
    }
   ]
  }
 ]
}